### ISSUE TITLE
Sidebar on Home Plans page does not appear

### ISSUE THREAD

**Issue by spalko** [CCI-Studios/Danbury-Homes#19]
There is just whitespace where the Sign up functionality should be on the sidebar.  

Screenshot attached.
<img width="945" alt="Screen Shot 2019-06-19 at 9 24 19 AM" src="https://user-images.githubusercontent.com/692091/59769454-308e3b00-9274-11e9-982b-e62206494e11.png">

**Comment by ccmorris** [comment]
closed by a0d7adb
